server:
  port: 8800

eureka:
  instance:
    prefer-ip-address: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761

spring:
  security:
    oauth2:
      resourceServer:
        issuer-uri: http://localhost:8080/realms/utopis-realm